### ISSUE TITLE
Doubt Clarification

### ISSUE THREAD

**Issue by dineshcodes999** [MicroTechEE/MSP430-I2C#1]
Hi MicroTechEE,

I hope this message finds you well. My name is Dinesh and I'm currently working on a project that involves the MSP430F5529 and I2C communication.

I'm facing some issues with the I2C code also not able to understand how i can communicate with external slave device.
i just want to read a register value from a particular slave address in CCS serial monitor.

could you please help me with that

Thank you for your time and let me know if you need any additional information.

Best regards,
Dinesh

**Comment by plentyofbytes** [comment]
Hey Dinesh,

Can you post your logic analyzer results? I could help more if I knew what was happening. Also make sure to change all the #defines in i2c.h . Make sure your GPIO are configure correctly. Also make sure that the msp430.h file references your exact model of MSP430. It should, but just confirm.

When reading from a peripheral device, typically you send a Write followed by what address you want to read from, then a Read followed by however may bytes you are reading. Some devices work differently, wherein you just give them a Write and then a Read with no bytes after the Write. I will release a new update where this is possible. All of this is all handled for you in the code. If I knew your exact problem, I could help, but I don't have much to go on.

Regarding the CCS serial monitor, I've never used it but I imagine it uses a COM port on your computer. The basic rules apply for debugging that as well, baud, COM port, and correct UART configuration on your MCU.

Getting me a logic analyzer capture file would allow me to help further.

**Comment by dineshcodes999** [comment]
Thanks you for your valuable reply,
I'm new to this msp430 micro controllers..

so, I'm looking for the code.. I tried to implement your program structure but not able to under stand properly..

what i have to do is i just have to read a register value in my slave device(MAX17055)

coming to serial monitor i just known how can i properly use that..

any help would be greatly appreciated..

best regards,
Dinesh

**Comment by plentyofbytes** [comment]
You need to find out which I2C Module inside the msp you are using. For instance, there are EUSCI B0 and B1 in your MSP. I looked in your datasheet to show you how to configure your I2C UCA module's GPIO:

![image](https://user-images.githubusercontent.com/71229123/234580328-71d15869-c27a-43a8-881f-fa8d37a4f1da.png)

This is an example for UCB0. If you're using UCB0 you would configure pins P3.0 and P3.1 as your I2C SDA and SCL pins. Then you would set P3SEL register bits BIT0 and BIT1 according to the image I just posted. If you are using UCB1, search for UCB1SDA in your datasheet and you will see a table eventually that tells you how to configure your MCU's GPIO.

With respect to this code, you will need to go through i2c.h and change anything that says UCB2xxxx to UCB0xxxx and make sure all the #defines make sense for the module you're using. If you decide to use UCB1 module, change everything to 1 instead of 0. Also make sure you update the #define for I2C_DEFAULT_PERIPHERAL_ADDRESS. I currently have it as an #error directive to force you to update it. 

There are dozens of things that be wrong with your code, but I can't help you with everything. If you have criticism to improve this code, I'm happy to look into it, but if you're looking for general guidance, search through and post on the TI E2E Forums.

I hope this helps you.

**Comment by dineshcodes999** [comment]
thanks for your reply,
i changed that registers still i can't able to understand the programming flow..
can you please able to send the program example which will only read the register value of an external slave device..
any small clue would be a great help..

best regards,
Dinesh

**Comment by dineshcodes999** [comment]
MSP430F5529 supports only USCI_I2C module your device was on different level..

please help me to know only this thing..

Thankfully,
Dinesh

**Comment by plentyofbytes** [comment]
The sample program you are asking for is in main.c . You can see how things work there. Regarding the #defines, both of our MCUs use the same reference manual, so your defines should resolve correctly. Can you post a screenshot of what your i2c.h looks like ( or attach it )?

**Comment by dineshcodes999** [comment]
yeah i'm trying to understand your program slowly..

https://dev.ti.com/tirex/explore/node?node=A__AIX66u3gk3PGevRBI2k1bA__msp430ware__IOGqZri__LATEST

here you can see MSP430F5529 USCI_I2C file..

best regards,
Dinesh

**Comment by plentyofbytes** [comment]
Would you please post a screenshot or attach your **i2c.h** with your #defines? I want to see your work. I don't need the driverlib. Thank you

**Comment by dineshcodes999** [comment]
My apologies for the delay..

I'm not using extra file for I2C.. 

I'm directly implementing the registers in the program as i attached below..

<img width="523" alt="Annotation 2023-04-27 110507" src="https://user-images.githubusercontent.com/82602541/234769050-ec8bfb2f-0ad2-40d9-b233-d64a133a095d.png">

**Comment by plentyofbytes** [comment]
I would like to have seen the whole function. I now realize asking for a screenshot wouldn't work even for the header I initially requested. All of these files are too large. I'll help with what I can.

<img width="523" alt="dineshSource" src="https://user-images.githubusercontent.com/71229123/234867209-a25fec29-b356-44dd-bd3a-dfa94db28447.png">

BLUE - You are setting UCSWRST ( 0x01 ) using the CTL register as a _Word_ and also as a byte. When you set it as a word using CTLW0, you are setting bit0 in the CTL0 register which is the UCSYNC bit. This is bit actually does need set, but make this more clear. I would use CTL0 and CTL1 and not use CTLW0 altogether to make it more clear.
YELLOW - Avoid while loops in Tx/Rx as much as possible, this is also completely unnecessary, the MCU **_sends the peripheral address for you as soon as a START condition is generated_**. I suspect your code is just hanging here forever due to my GREEN mark
RED - As stated in Yellow, the MCU send the Peripheral Address automatically on START, your first byte needs to be what register you're writing to
GREEN - I do not see where you are enabling interrupts. Without interrupts, IFG never gets set, and your code in Yellow will be stuck there forever. 

I hope this helps. Next, I don't want to leave you stranded here, but this is effectively not the code from this repo anymore. I've done what I can to help you, but this is no longer what I've written, which is okay. It's great that what I wrote can be a piece of what you're creating. I just can't support/troubleshoot it. 

Make these corrections, and you'll be well on your way. Also make sure your prescaler is correct in BRO0 BR1. It looks like on a 8MHz clock, your I2C clock is 100kHz which is one of the 3 common frequencies, good. Also make sure you Peripheral address in UCB1I2CSA is Right Justified. The MCU will shift this by 1 bit for you automatically.

I really hope this helps.

**Comment by plentyofbytes** [comment]
As a side note, also understand that Reading is done by writing to the register you want to read from, STOP, START, then Read. Your actual read code may need work too. I didn't get to see it. Really the biggest difference is Clearing UCTR instead of Setting it.

Set UCSWRST before all your register changes and Clear UCSWRST after your changes are done. I would try using my i2c files as they are on a Lower Level, and using them in your Sensor.c file which would be your higher level code. This is referred to as _abstraction_. Just try using my files as they are and you will be much more likely to succeed. There's no point in re-inventing the wheel here.

And even if its a cheap one, get a logic analyzer.

All the best,

**Comment by dineshcodes999** [comment]
Thank you for your valuable suggestions..

I'm completely new to msp430 micro controllers..

till now i tried the examples given by TI but still i'm not able to understand..
kindly please give me any code that only reads the register value from slave device..

Best Regards,
Dinesh

**Comment by plentyofbytes** [comment]
I understand. I still remember being new, and yes TI code just plain sucks. There's no better way to put it.

The code you downloaded from this repo is precisely what you are asking for. Use i2c_read() and i2c_write() from i2c.c in this repo. I have done all the work for you, you just have to change the #defines in i2c.h to use UCB1 instead of UCB2. Also you need to update the Peripheral address #define in .h . Make sure you change EUSCI_BASE_B2 to EUSCI_BASE_B1. **Pay close attention to everything in i2c.h**.

Also, I want you to download the files into a zip on your PC and literally drag i2c.c and i2c.h into your project files. Make sure you #include "i2c.h" into any files you are using this code.

I assure you, this is the key to fixing your issue so you can make your sensor work.

**Comment by dineshcodes999** [comment]
Yeah I'm trying to understand your code rather than looking for another code..
thanks for your valuable timing spending with me..

best regards,
Dinesh

**Comment by plentyofbytes** [comment]
You're welcome.

The beauty of the code is that you can use it first, just to get going, and then you can begin to understand it later.

I've learned this is the best. I always want to understand everything immediately, but that takes a very long time. Just get it to work, and then you can study it later.

Good luck
